### ISSUE TITLE
[BUG] Warning: componentWillReceiveProps has been renamed - react-formio Form component. 

### ISSUE THREAD

**Issue by jepz** [formio/react-formio#336] opened 2020-09-24 15:38 UTC
I have started receiving this error when closing / unmounting react-formIo component, it's in a functional component. 

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Form

Version:
  "formiojs": "^4.11.0",
"react-formio": "^4.3.0",
"react": "^16.13.1",

**Comment by rtenhove** [comment] 2020-10-09 14:06
Duplicate of [issue 290](https://github.com/formio/react-formio/issues/290).

**Comment by wag110894** [comment] 2020-10-23 19:10
React has now been upgraded to 16.13.1. 

Please let me know if you have any further questions.

**Closed by wag110894** 2020-10-23 19:10 UTC
Labels: bug
