### ISSUE TITLE
Empty required select is valid onChange

### ISSUE THREAD

**Issue by justjuank** [formio/react-formio#132] opened 2018-09-05 16:58 UTC
Hi, I'm using the onChange event on the <Form> component and when I use a select control with required checked, the onChange event passes isValid as true when the select is empty. The submit button however, gets disabled correctly. I think it's just the callback.
This seems like a bug to me. I'm not using the form.io buttons, I have my own buttons in my app and wanted to disable my buttons based on the isValid parameter that I get from the onChange event.

Any workaround for this?

Thanks,

Juan.

**Comment by sireeshav** [comment] 2019-01-09 01:48
@justjuank  did u get the fix. I need it too . Please help. For me even formio submit button isnt getting disabled on any of field validation.

**Comment by justjuank** [comment] 2019-01-09 16:53
@sireeshav unfortunately I don't have a fix yet
@randallknutson I'm using react-formio version 3.0.1 
I haven't upgraded since then so I don't know if this is fixed in a greater version.

**Comment by ybo** [comment] 2019-02-26 00:52
I have the same use case (having my own button) and I encounter the same problem with @justjuank , that is isValid is true even if required fields are empty. 

One thing I notice is that if you type something into a required field and then delete it, isValid is set to false correctly. So basically isValid === false if and only if a red validation error message shows up. It should behave exactly the same as the submit button (i.e. invalid if required field is not dirty).

**Comment by randallknutson** [comment] 2019-02-26 15:47
It does sound like there is an issue here. We can add it to our bug list to get fixed which may take a little time to get to. Is this something one of you would be able to look into? We also have an option to expedite bugs that are important to customers.

**Comment by ybo** [comment] 2019-02-26 18:25
I spent some time yesterday and I couldn't find the root cause. tbh I cannot even tell if the issue is in react-formio or formiojs.

**Comment by ybo** [comment] 2019-04-02 21:34
@randallknutson Hi any update on this? Thanks

**Comment by travist** [comment] 2019-04-03 14:37
This item should have been fixed with the 3.18.0 version of our core renderer (which this library depends on). Can you verify if this is resolved when you pull in the latest core renderer?

```
npm install --save formiojs
```

**Comment by ybo** [comment] 2019-04-03 17:56
I will verify this and get back to you. Thanks for the info :)

**Comment by ybo** [comment] 2019-04-05 00:25
@travist I pulled the latest core and I don't think it is fixed. It is still behaving as before.
Also I found that https://github.com/formio/formio.js/pull/1094 is reverted. I understand why that change is reverted, but that means this bug is still not fixed :(

Let me know if I should open an issue in https://github.com/formio/formio.js

Thanks

**Comment by jhen1422** [comment] 2019-09-06 21:14
@ybo Please update to the latest version - issue should be resolved.

**Closed by jhen1422** 2019-09-06 21:14 UTC
